ServerName localhost

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule alias_module modules/mod_alias.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so

User daemon
Group daemon

Listen 80

ServerAdmin you@example.com
DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    AllowOverride None
    Require all granted
</Directory>

<Proxy "balancer://frontendcluster">
    BalancerMember http://frontend1:80
    BalancerMember http://frontend2:80
    ProxySet lbmethod=byrequests
</Proxy>

ProxyPass "/" "balancer://frontendcluster/"
ProxyPassReverse "/" "balancer://frontendcluster/"

<Location "/balancer-manager">
    SetHandler balancer-manager
    Require all granted
</Location>
