LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# 🔁 Algoritmo 1: Round Robin
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so

# 🔁 Algoritmo 2: Least Connections
LoadModule lbmethod_bybusyness_module modules/mod_lbmethod_bybusyness.so


<Proxy "balancer://cluster">
    BalancerMember http://backend1:80
    BalancerMember http://backend2:80
    BalancerMember http://backend3:80

    # 🔄 CAMBIAR SEGÚN PRUEBA

    # Round Robin (ACTUAL)
    ProxySet lbmethod=byrequests

    # Least Connections (DESCOMENTAR PARA PROBAR)
    # ProxySet lbmethod=bybusyness
</Proxy>

ProxyPass "/" "balancer://cluster/"
ProxyPassReverse "/" "balancer://cluster/"
